version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5100:5100"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mutyro
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mutyro-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:5100
      # - VITE_API_URL=http://backend:5100
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mutyro-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mutyro-network

volumes:
  mongodb_data:

networks:
  mutyro-network:
    driver: bridge
