export const MUTIRAO_STATUS = {
  ACTIVE: "ATIVO",
  INACTIVE: "INATIVO",
  PENDING: "PENDENTE",
  IN_PROGRESS: "EM_ANDAMENTO",
  DONE: "CONCLUIDO",
  ERROR: "ERRO",
};

export const MUTIRAO_SORT_BY = {
  NEWEST_FIRST: 'newest',
  OLDEST_FIRST: 'oldest',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
};

export const MUTIRAO_TIPOS = {
  SOCIAL: 'SOCIAL',
  CONSTRUCAO_REFORMA: 'CONSTRUCAO_REFORMA', 
  AMBIENTAL_AGRICOLA: 'AMBIENTAL_AGRICOLA', 
  CULTURA_EDUCACAO: 'CULTURA_EDUCACAO', 
  SAUDE: 'SAUDE',
  TECNOLOGIA: 'TECNOLOGIA',
};