export const MUTIRAO_STATUS = {
    PENDING: 'PENDENTE',
    IN_PROGRESS: 'EM_ANDAMENTO',
    DONE: 'CONCLUIDO',
    ERROR: 'ERRO',
};

export const MUTIRAO_SORT_BY = {
  NEWEST_FIRST: 'newest',
  OLDEST_FIRST: 'oldest',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
};

export const MUTIRAO_TIPOS = {
  AMBIENT_AGRO: "AMBIENTAL/AGRICOLA",
  CONST_REFORM: "CONSTRUCAO/REFORMA",
  SOCIAL: "SOCIAL",
  CULT_EDUCA: "CULTURA/EDUCACAO",
  SAUDE: "SAUDE",
  TECNOLOGICO: "TECNOLOGIA",
};